# rfm adaptor configuration

#--------------------#
# environments

development:
  host:     "FileMakerServer.localnet"  # FileMakerServer's IP-address or hostname
  port:     80
  ssl:      false
  username: "Administrator"
  password: "password"
  
test:
  host:     "FileMakerServer.localnet"  # FileMakerServer's IP-address or hostname
  port:     80
  ssl:      false
  username: "Administrator"
  password: "password"
  
production:
  host:     "FileMakerServer.localnet"  # FileMakerServer's IP-address or hostname
  port:     80
  ssl:      false
  username: "Administrator"
  password: "password"
