# rfm adaptor configuration

#--------------------#
# connections

default:
    host:     "FileMakerServer"  # FileMakerServer's IP-address or hostname
    port:     80
    ssl:      false
    username: "Administrator"
    password: "password"
