# rfm adaptor configuration

#--------------------#
# connections

server1:
  development:
    host:     "server1.development_network"  # FileMakerServer's IP-address or hostname
    port:     80
    ssl:      false
    username: "Administrator"
    password: "password"
    
  test:
    host:     "server1.test_network"  # FileMakerServer's IP-address or hostname
    port:     80
    ssl:      false
    username: "Administrator"
    password: "password"
    
  production:
    host:     "server1"  # FileMakerServer's IP-address or hostname
    port:     80
    ssl:      false
    username: "Administrator"
    password: "password"
