# rfm adaptor configuration

#--------------------#
# connections

test_server:
    host:     "fmsv-test"  # FileMakerServer's IP-address or hostname
    port:     80
    ssl:      false
    username: "test_user"
    password: "test_password"
