# rfm adaptor configuration

#--------------------#
# connections

test_server:
    host:     "test_server.localnet"  # FileMakerServer's IP-address or hostname
    port:     80
    ssl:      false
    username: "Administrator"
    password: "password"
